# Generated by Django 2.1.7 on 2019-03-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20190330_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalnotification',
            name='Pay',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='globalnotification',
            name='Working_Hour',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='globalnotification',
            name='Date',
            field=models.DateField(blank=True, help_text='Please enter in the format mm/dd/yyyy', null=True),
        ),
    ]
